version: "2"         # required to adjust maintainability checks
checks:
  argument-count:
    config:
      threshold: 55
  complex-logic:
    config:
      threshold: 40
  file-lines:
    config:
      threshold: 350
  method-complexity:
    config:
      threshold: 35
  method-count:
    config:
      threshold: 50
  method-lines:
    config:
      threshold: 250
  nested-control-flow:
    config:
      threshold: 10
  return-statements:
    config:
      threshold: 10
  similar-code:
    config:
      threshold: # language-specific defaults. an override will affect all languages.
  identical-code:
    config:
      threshold: # language-specific defaults. an override will affect all languages.
exclude_patterns:
- "node_modules/"
- "test/"
- "src/data.js"
plugins:
  editorconfig:
    enabled: true
  eslint:
    enabled: true
  fixme:
    enabled: true
  nodesecurity:
    enabled: true
  shellcheck:
    enabled: true
  stylelint:
    enabled: true
